# wrangler.toml
name = "vatsmonitor"
compatibility_date = "2025-05-03"

# Seiten-Build-Ausgabe (Next.js + @cloudflare/next-on-pages erzeugt hier die statischen Assets)
pages_build_output_dir = ".vercel/output/static"

[build]
  # Dein lokaler Build-Befehl
  command = "npm run build"
  # Verzeichnis, das nach dem Build hochgeladen wird
  upload = { format = "directory", dir = ".vercel/output/static" }

# Environment-Variablen, die beim Build und zur Laufzeit verfügbar sind:
[vars]
NEXT_PUBLIC_SUPABASE_URL     = "https://vmkyapnksqhperwyqged.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZta3lhcG5rc3FocGVyd3lxZ2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDY3OTAsImV4cCI6MjA2MTQyMjc5MH0.C2dQONrcvq99wHexgXFIk0R-lrnXNyoF3MbqC-6S4CA"
